# Generated by Django 2.1.7 on 2019-04-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0003_auto_20190418_1318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pNo', models.CharField(max_length=7)),
                ('pBrand', models.CharField(max_length=100)),
                ('pPrice', models.CharField(max_length=20)),
                ('pContent', models.CharField(max_length=100)),
                ('pFile', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='phone',
        ),
    ]
